"""Build-time Developer Trust anchors for Official Developer Access.

AUTO-GENERATED BY scripts/embed_developer_root.py. Only public trust material belongs here.
Never place Root/Issuing/Developer private keys in the public Arenyxa source tree.
"""

EMBEDDED_DEVELOPER_ROOTS = ({'algorithm': 'Ed25519',
  'created_at': '2026-08-19T07:19:10+00:00',
  'fingerprint': 'ARYX-C3D043C2-DBA50302-9851306A-3B59272B-71ED9491-7694AA8F-A2FD37BF-AF851636',
  'key_id': 'devroot_c3d043c2dba503029851',
  'owner_label': 'Arenyxa Developer Root',
  'public_key': '3yW89Xzmhyjg_codQaZmmVzYi--5HTNRJk_B1DCQEEo',
  'schema': 'arenyxa.developer-root-trust/v1',
  'signature': {'algorithm': 'Ed25519',
                'signer_key_id': 'devroot_c3d043c2dba503029851',
                'value': 'ojHhz36EMP9-EASgziGQYfM3PiJDH9GfqL9N-z_IBsaVqlhZUo8DUQMHJl8WMHnQw_Y2qg6PJ_sZ6TPIobBYDg'}},)

EMBEDDED_DEVELOPER_REVOCATIONS = ()
