"""Enterprise and privileged-access localization extension for Arenyxa UI."""

from __future__ import annotations

ENTERPRISE_PHRASES: dict[str, str] = {'Official Developer 与公开 Developer Profile 完全分离：必须验证 Developer Certificate 信任链，再用对应设备上的 Developer Personal Private Key 完成一次性挑战。邮箱不是安全根；Enterprise 管理员也不会自动获得这些能力。': 'Official '
                                                                                                                                                                    'Developer '
                                                                                                                                                                    'Access '
                                                                                                                                                                    'is '
                                                                                                                                                                    'separate '
                                                                                                                                                                    'from '
                                                                                                                                                                    'the '
                                                                                                                                                                    'public '
                                                                                                                                                                    'Developer '
                                                                                                                                                                    'Profile: '
                                                                                                                                                                    'the '
                                                                                                                                                                    'Developer '
                                                                                                                                                                    'Certificate '
                                                                                                                                                                    'chain '
                                                                                                                                                                    'must '
                                                                                                                                                                    'validate '
                                                                                                                                                                    'and '
                                                                                                                                                                    'the '
                                                                                                                                                                    'matching '
                                                                                                                                                                    'device-held '
                                                                                                                                                                    'Developer '
                                                                                                                                                                    'Personal '
                                                                                                                                                                    'Private '
                                                                                                                                                                    'Key '
                                                                                                                                                                    'must '
                                                                                                                                                                    'complete '
                                                                                                                                                                    'a '
                                                                                                                                                                    'one-time '
                                                                                                                                                                    'challenge. '
                                                                                                                                                                    'Email '
                                                                                                                                                                    'is '
                                                                                                                                                                    'not '
                                                                                                                                                                    'a '
                                                                                                                                                                    'trust '
                                                                                                                                                                    'root, '
                                                                                                                                                                    'and '
                                                                                                                                                                    'Enterprise '
                                                                                                                                                                    'administrators '
                                                                                                                                                                    'do '
                                                                                                                                                                    'not '
                                                                                                                                                                    'inherit '
                                                                                                                                                                    'these '
                                                                                                                                                                    'capabilities.',
 'Official Developer 与公开 Developer Profile 完全分离：必须验证 Developer Certificate 信任链，再用对应设备私钥完成一次性挑战。Root Owner 使用独立 Owner/Authority credential；Developer Root Private Key 不参与日常登录并应始终保持离线。邮箱不是安全根；Enterprise 管理员也不会自动获得这些能力。': 'Official '
                                                                                                                                                                                                                          'Developer '
                                                                                                                                                                                                                          'Access '
                                                                                                                                                                                                                          'is '
                                                                                                                                                                                                                          'separate '
                                                                                                                                                                                                                          'from '
                                                                                                                                                                                                                          'the '
                                                                                                                                                                                                                          'public '
                                                                                                                                                                                                                          'Developer '
                                                                                                                                                                                                                          'Profile: '
                                                                                                                                                                                                                          'validate '
                                                                                                                                                                                                                          'the '
                                                                                                                                                                                                                          'Developer '
                                                                                                                                                                                                                          'Certificate '
                                                                                                                                                                                                                          'chain, '
                                                                                                                                                                                                                          'then '
                                                                                                                                                                                                                          'prove '
                                                                                                                                                                                                                          'the '
                                                                                                                                                                                                                          'matching '
                                                                                                                                                                                                                          'device '
                                                                                                                                                                                                                          'private '
                                                                                                                                                                                                                          'key '
                                                                                                                                                                                                                          'with '
                                                                                                                                                                                                                          'a '
                                                                                                                                                                                                                          'one-time '
                                                                                                                                                                                                                          'challenge. '
                                                                                                                                                                                                                          'Root '
                                                                                                                                                                                                                          'Owner '
                                                                                                                                                                                                                          'uses '
                                                                                                                                                                                                                          'a '
                                                                                                                                                                                                                          'separate '
                                                                                                                                                                                                                          'Owner/Authority '
                                                                                                                                                                                                                          'credential; '
                                                                                                                                                                                                                          'the '
                                                                                                                                                                                                                          'Developer '
                                                                                                                                                                                                                          'Root '
                                                                                                                                                                                                                          'Private '
                                                                                                                                                                                                                          'Key '
                                                                                                                                                                                                                          'does '
                                                                                                                                                                                                                          'not '
                                                                                                                                                                                                                          'participate '
                                                                                                                                                                                                                          'in '
                                                                                                                                                                                                                          'routine '
                                                                                                                                                                                                                          'login '
                                                                                                                                                                                                                          'and '
                                                                                                                                                                                                                          'remains '
                                                                                                                                                                                                                          'offline. '
                                                                                                                                                                                                                          'Email '
                                                                                                                                                                                                                          'is '
                                                                                                                                                                                                                          'not '
                                                                                                                                                                                                                          'a '
                                                                                                                                                                                                                          'trust '
                                                                                                                                                                                                                          'root, '
                                                                                                                                                                                                                          'and '
                                                                                                                                                                                                                          'Enterprise '
                                                                                                                                                                                                                          'administrators '
                                                                                                                                                                                                                          'do '
                                                                                                                                                                                                                          'not '
                                                                                                                                                                                                                          'inherit '
                                                                                                                                                                                                                          'these '
                                                                                                                                                                                                                          'capabilities.',
 'Official Developer 与公开 Developer Profile 完全分离：必须验证 Developer Certificate 信任链，再用对应设备私钥完成一次性挑战。Root Owner 不在普通设置界面提供登录入口；已注册 Root Workstation 会在每次启动主界面前强制重新验证 Owner Device Key。Developer Root Private Key 始终保持离线。': 'Official '
                                                                                                                                                                                                                     'Developer '
                                                                                                                                                                                                                     'Access '
                                                                                                                                                                                                                     'is '
                                                                                                                                                                                                                     'separate '
                                                                                                                                                                                                                     'from '
                                                                                                                                                                                                                     'the '
                                                                                                                                                                                                                     'public '
                                                                                                                                                                                                                     'Developer '
                                                                                                                                                                                                                     'Profile: '
                                                                                                                                                                                                                     'validate '
                                                                                                                                                                                                                     'the '
                                                                                                                                                                                                                     'Developer '
                                                                                                                                                                                                                     'Certificate '
                                                                                                                                                                                                                     'chain, '
                                                                                                                                                                                                                     'then '
                                                                                                                                                                                                                     'prove '
                                                                                                                                                                                                                     'the '
                                                                                                                                                                                                                     'matching '
                                                                                                                                                                                                                     'device '
                                                                                                                                                                                                                     'private '
                                                                                                                                                                                                                     'key '
                                                                                                                                                                                                                     'with '
                                                                                                                                                                                                                     'a '
                                                                                                                                                                                                                     'one-time '
                                                                                                                                                                                                                     'challenge. '
                                                                                                                                                                                                                     'Root '
                                                                                                                                                                                                                     'Owner '
                                                                                                                                                                                                                     'has '
                                                                                                                                                                                                                     'no '
                                                                                                                                                                                                                     'sign-in '
                                                                                                                                                                                                                     'entry '
                                                                                                                                                                                                                     'in '
                                                                                                                                                                                                                     'ordinary '
                                                                                                                                                                                                                     'Settings; '
                                                                                                                                                                                                                     'a '
                                                                                                                                                                                                                     'registered '
                                                                                                                                                                                                                     'Root '
                                                                                                                                                                                                                     'Workstation '
                                                                                                                                                                                                                     'must '
                                                                                                                                                                                                                     'revalidate '
                                                                                                                                                                                                                     'the '
                                                                                                                                                                                                                     'Owner '
                                                                                                                                                                                                                     'Device '
                                                                                                                                                                                                                     'Key '
                                                                                                                                                                                                                     'before '
                                                                                                                                                                                                                     'the '
                                                                                                                                                                                                                     'main '
                                                                                                                                                                                                                     'interface '
                                                                                                                                                                                                                     'opens '
                                                                                                                                                                                                                     'on '
                                                                                                                                                                                                                     'every '
                                                                                                                                                                                                                     'launch. '
                                                                                                                                                                                                                     'The '
                                                                                                                                                                                                                     'Developer '
                                                                                                                                                                                                                     'Root '
                                                                                                                                                                                                                     'Private '
                                                                                                                                                                                                                     'Key '
                                                                                                                                                                                                                     'remains '
                                                                                                                                                                                                                     'offline.',
 '登录 Official Developer': 'Sign in as Official Developer',
 'Identity / Enrollment / Coordinator / Governance / Distributed Runtime': 'Identity / Enrollment / Coordinator / '
                                                                           'Governance / Distributed Runtime',
 'Enrollment / Device Trust / Domain Lock': 'Enrollment / Device Trust / Domain Lock',
 'Office Enterprise Coordinator': 'Office Enterprise Coordinator',
 'Enterprise Workspace Governance': 'Enterprise Workspace Governance',
 'Enterprise Server / Distributed Worker': 'Enterprise Server / Distributed Worker',
 '退出 Official Developer': 'Sign out Official Developer',
 'Local Enterprise Identity 已可用：可以在本机创建 Enterprise ID、加密 Identity Vault、Local Super Administrator 和 RBAC；Enrollment 与 Device Trust 由独立企业治理模块处理。': 'Local '
                                                                                                                                                  'Enterprise '
                                                                                                                                                  'Identity '
                                                                                                                                                  'is '
                                                                                                                                                  'available: '
                                                                                                                                                  'create '
                                                                                                                                                  'an '
                                                                                                                                                  'Enterprise '
                                                                                                                                                  'ID, '
                                                                                                                                                  'encrypted '
                                                                                                                                                  'Identity '
                                                                                                                                                  'Vault, '
                                                                                                                                                  'Local '
                                                                                                                                                  'Super '
                                                                                                                                                  'Administrator, '
                                                                                                                                                  'and '
                                                                                                                                                  'RBAC '
                                                                                                                                                  'on '
                                                                                                                                                  'this '
                                                                                                                                                  'device; '
                                                                                                                                                  'Enrollment '
                                                                                                                                                  'and '
                                                                                                                                                  'Device '
                                                                                                                                                  'Trust '
                                                                                                                                                  'are '
                                                                                                                                                  'handled '
                                                                                                                                                  'by '
                                                                                                                                                  'the '
                                                                                                                                                  'dedicated '
                                                                                                                                                  'enterprise-governance '
                                                                                                                                                  'modules.',
 '打开本地企业管理': 'Open Local Enterprise Administration',
 '加入企业 · Enrollment 可用后启用': 'Join Enterprise · available when Enrollment is configured',
 '创建本地企业': 'Create Local Enterprise',
 '解锁 Identity Vault': 'Unlock Identity Vault',
 '企业登录': 'Enterprise Sign-in',
 '退出企业会话': 'Sign out Enterprise Session',
 '锁定 Vault': 'Lock Vault',
 '角色只是产品预设；真正授权由 SecurityKernel 的 capability / policy / resource / context 决策。禁用账户、修改角色或密码会递增 auth_generation，并立即撤销对应本机会话。': 'Roles '
                                                                                                                             'are '
                                                                                                                             'product '
                                                                                                                             'presets; '
                                                                                                                             'authorization '
                                                                                                                             'is '
                                                                                                                             'decided '
                                                                                                                             'by '
                                                                                                                             'SecurityKernel '
                                                                                                                             'capability '
                                                                                                                             '/ '
                                                                                                                             'policy '
                                                                                                                             '/ '
                                                                                                                             'resource '
                                                                                                                             '/ '
                                                                                                                             'context. '
                                                                                                                             'Disabling '
                                                                                                                             'an '
                                                                                                                             'account '
                                                                                                                             'or '
                                                                                                                             'changing '
                                                                                                                             'its '
                                                                                                                             'role/password '
                                                                                                                             'increments '
                                                                                                                             'auth_generation '
                                                                                                                             'and '
                                                                                                                             'immediately '
                                                                                                                             'revokes '
                                                                                                                             'the '
                                                                                                                             'corresponding '
                                                                                                                             'local '
                                                                                                                             'session.',
 '刷新账户': 'Refresh Accounts',
 '新增账户': 'Add Account',
 '禁用 / 启用账户': 'Disable / Enable Account',
 '修改角色': 'Change Roles',
 '修改密码': 'Change Password',
 '删除账户': 'Delete Account',
 'Vault 使用认证加密、版本化格式和同目录原子替换。备份与高风险账户治理要求最近一次 step-up authentication。恢复只能在 Vault 锁定时执行，避免用新持久状态替换仍在运行的旧授权会话。': 'The '
                                                                                                               'Vault '
                                                                                                               'uses '
                                                                                                               'authenticated '
                                                                                                               'encryption, '
                                                                                                               'a '
                                                                                                               'versioned '
                                                                                                               'format, '
                                                                                                               'and '
                                                                                                               'same-directory '
                                                                                                               'atomic '
                                                                                                               'replacement. '
                                                                                                               'Backup '
                                                                                                               'and '
                                                                                                               'high-risk '
                                                                                                               'account '
                                                                                                               'governance '
                                                                                                               'require '
                                                                                                               'recent '
                                                                                                               'step-up '
                                                                                                               'authentication. '
                                                                                                               'Restore '
                                                                                                               'is '
                                                                                                               'allowed '
                                                                                                               'only '
                                                                                                               'while '
                                                                                                               'the '
                                                                                                               'Vault '
                                                                                                               'is '
                                                                                                               'locked '
                                                                                                               'so '
                                                                                                               'new '
                                                                                                               'persistent '
                                                                                                               'state '
                                                                                                               'cannot '
                                                                                                               'replace '
                                                                                                               'authorization '
                                                                                                               'underneath '
                                                                                                               'live '
                                                                                                               'sessions.',
 '备份 Vault': 'Back Up Vault',
 '恢复 Vault': 'Restore Vault',
 '加入企业、Enrollment Credential、Device Trust、Enterprise Domain Lock 和 Office Coordinator 仅在真实设备身份、防重放协议和受信任企业根已建立时开放；LAN Discovery 本身不是信任边界。': 'Join '
                                                                                                                                            'Enterprise, '
                                                                                                                                            'Enrollment '
                                                                                                                                            'Credential, '
                                                                                                                                            'Device '
                                                                                                                                            'Trust, '
                                                                                                                                            'Enterprise '
                                                                                                                                            'Domain '
                                                                                                                                            'Lock, '
                                                                                                                                            'and '
                                                                                                                                            'Office '
                                                                                                                                            'Coordinator '
                                                                                                                                            'are '
                                                                                                                                            'exposed '
                                                                                                                                            'only '
                                                                                                                                            'after '
                                                                                                                                            'real '
                                                                                                                                            'device '
                                                                                                                                            'identity, '
                                                                                                                                            'replay '
                                                                                                                                            'defense, '
                                                                                                                                            'and '
                                                                                                                                            'a '
                                                                                                                                            'trusted '
                                                                                                                                            'Enterprise '
                                                                                                                                            'Root '
                                                                                                                                            'are '
                                                                                                                                            'established; '
                                                                                                                                            'LAN '
                                                                                                                                            'discovery '
                                                                                                                                            'itself '
                                                                                                                                            'is '
                                                                                                                                            'not '
                                                                                                                                            'a '
                                                                                                                                            'trust '
                                                                                                                                            'boundary.',
 '加入企业': 'Join Enterprise',
 'Enterprise 已进入本地身份、Enrollment、Device Trust、Office Coordinator 与 Workspace Governance 阶段。创建企业和企业治理使用独立的企业管理流程；加入企业需要一次性 Enrollment Credential。': 'Enterprise '
                                                                                                                                                  'now '
                                                                                                                                                  'includes '
                                                                                                                                                  'local '
                                                                                                                                                  'identity, '
                                                                                                                                                  'Enrollment, '
                                                                                                                                                  'Device '
                                                                                                                                                  'Trust, '
                                                                                                                                                  'Office '
                                                                                                                                                  'Coordinator, '
                                                                                                                                                  'and '
                                                                                                                                                  'Workspace '
                                                                                                                                                  'Governance. '
                                                                                                                                                  'Enterprise '
                                                                                                                                                  'creation '
                                                                                                                                                  'and '
                                                                                                                                                  'governance '
                                                                                                                                                  'use '
                                                                                                                                                  'a '
                                                                                                                                                  'dedicated '
                                                                                                                                                  'administration '
                                                                                                                                                  'flow; '
                                                                                                                                                  'joining '
                                                                                                                                                  'requires '
                                                                                                                                                  'a '
                                                                                                                                                  'one-time '
                                                                                                                                                  'Enrollment '
                                                                                                                                                  'Credential.',
 '打开企业管理': 'Open Enterprise Administration',
 'Enterprise Server / Distributed Worker 复用同一套 Core Runtime。打开企业管理可查看 Server、Worker、队列与远程运维状态。': 'Enterprise Server '
                                                                                                 '/ Distributed '
                                                                                                 'Worker reuses the '
                                                                                                 'same Core Runtime. '
                                                                                                 'Open Enterprise '
                                                                                                 'Management to '
                                                                                                 'inspect Server, '
                                                                                                 'Worker, queue, and '
                                                                                                 'remote-operations '
                                                                                                 'status.',
 '打开 Server / Worker 管理': 'Open Server / Worker Management',
 '之后可在 设置 → 使用模式 重新打开此独立窗口。主题、字体、缩放与动效继续放在独立“个性化”页面。': 'You can reopen this independent window later from Settings → '
                                                       'Experience. Themes, fonts, scaling, and motion remain in the '
                                                       'separate Personalization page.',
 '一次性 Enrollment Credential、批量 Campaign、设备公钥登记与 Domain Lock 已接入。': 'One-time Enrollment Credentials, batch '
                                                                   'campaigns, device public-key registration, and '
                                                                   'Domain Lock are available.',
 '为账户创建 Enrollment': 'Create Enrollment for Account',
 'CSV 批量导入 + Campaign': 'CSV Bulk Import + Campaign',
 '查看设备': 'View Devices',
 '撤销设备': 'Revoke Device',
 '加入 Office Enterprise': 'Join Office Enterprise',
 '重新连接 Office Enterprise': 'Reconnect Office Enterprise',
 'Coordinator 当前未运行。LAN Discovery 仅用于发现，真正信任由 Enterprise Root 签名身份 + TLS 证书绑定建立。': 'Coordinator is not running. LAN '
                                                                                   'Discovery is only for discovery; '
                                                                                   'trust is established by the '
                                                                                   'Enterprise Root-signed identity '
                                                                                   'plus TLS certificate binding.',
 '启动 Coordinator': 'Start Coordinator',
 '停止 Coordinator': 'Stop Coordinator',
 'Workspace / Team / Project 资源边界、资源级 RBAC、Quota、Approval 与 Audit Query 已接入治理层。': 'Workspace / Team / Project '
                                                                                  'boundaries, resource-level RBAC, '
                                                                                  'Quota, Approval, and Audit Query '
                                                                                  'are integrated into the '
                                                                                  'governance layer.',
 '创建 Workspace': 'Create Workspace',
 '登记受治理资源': 'Register Governed Resource',
 '查询最近 Audit': 'Query Recent Audit',
 'Enterprise Server 与 Worker 共享同一 Core Runtime / Task / Run 模型。Desktop 这里只提供受授权的远程运维视图；Server/Worker 本身仍通过独立 runtime/launcher 运行，不在 UI 内 fork 第二套执行引擎。': 'Enterprise '
                                                                                                                                                         'Server '
                                                                                                                                                         'and '
                                                                                                                                                         'Workers '
                                                                                                                                                         'share '
                                                                                                                                                         'the '
                                                                                                                                                         'same '
                                                                                                                                                         'Core '
                                                                                                                                                         'Runtime '
                                                                                                                                                         '/ '
                                                                                                                                                         'Task '
                                                                                                                                                         '/ '
                                                                                                                                                         'Run '
                                                                                                                                                         'model. '
                                                                                                                                                         'Desktop '
                                                                                                                                                         'exposes '
                                                                                                                                                         'only '
                                                                                                                                                         'authorized '
                                                                                                                                                         'remote-operations '
                                                                                                                                                         'views; '
                                                                                                                                                         'the '
                                                                                                                                                         'Server/Worker '
                                                                                                                                                         'runtimes '
                                                                                                                                                         'still '
                                                                                                                                                         'run '
                                                                                                                                                         'independently '
                                                                                                                                                         'and '
                                                                                                                                                         'never '
                                                                                                                                                         'fork '
                                                                                                                                                         'a '
                                                                                                                                                         'second '
                                                                                                                                                         'execution '
                                                                                                                                                         'engine '
                                                                                                                                                         'inside '
                                                                                                                                                         'the '
                                                                                                                                                         'UI.',
 '分布式队列健康': 'Distributed Queue Health',
 '查看 Worker': 'View Workers',
 '查看分布式 Job': 'View Distributed Jobs',
 '集中查看 Enterprise Server、Distributed Worker、并行 Slots、Jobs、Leases、存储拓扑与健康状态。Fleet Control 只提供已授权的运行与运维视图，不改变 Enterprise 权限边界。': 'Inspect '
                                                                                                                               'Enterprise '
                                                                                                                               'Server, '
                                                                                                                               'Distributed '
                                                                                                                               'Worker, '
                                                                                                                               'parallel '
                                                                                                                               'slots, '
                                                                                                                               'jobs, '
                                                                                                                               'leases, '
                                                                                                                               'storage '
                                                                                                                               'topology, '
                                                                                                                               'and '
                                                                                                                               'health '
                                                                                                                               'in '
                                                                                                                               'one '
                                                                                                                               'place. '
                                                                                                                               'Fleet '
                                                                                                                               'Control '
                                                                                                                               'exposes '
                                                                                                                               'only '
                                                                                                                               'authorized '
                                                                                                                               'runtime '
                                                                                                                               'and '
                                                                                                                               'operations '
                                                                                                                               'views '
                                                                                                                               'and '
                                                                                                                               'does '
                                                                                                                               'not '
                                                                                                                               'alter '
                                                                                                                               'Enterprise '
                                                                                                                               'authorization '
                                                                                                                               'boundaries.',
 '打开 Fleet Control': 'Open Fleet Control'}


ENTERPRISE_PHRASES.update({
    "模式负责进入企业工作环境；Identity、Fleet、Server、Worker、Jobs、Audit 与 Policy 的具体操作继续由 capability / Security Kernel 控制。": "The mode enters the enterprise workspace; specific Identity, Fleet, Server, Worker, Jobs, Audit, and Policy operations remain controlled by capabilities and the Security Kernel.",
    "选择 Personal Mode 时，Arenyxa 会用该场景配置首次进入的首页；之后仍可访问全部个人功能。": "When Personal Mode is selected, Arenyxa uses this scenario to choose the initial home page; all personal features remain available afterward.",
    "进入企业工作模式": "Enter Enterprise Workspace Mode",
    "模式负责进入企业工作环境；Identity、Fleet、Server、Worker、Jobs、Audit 与 Policy 的具体操作继续由 capability policy 授权。": "The mode enters the enterprise workspace; specific Identity, Fleet, Server, Worker, Jobs, Audit, and Policy operations remain authorized by capability policy.",
})


ENTERPRISE_PHRASES.update({
    "官方开发者授权": "Official Developer Authorization",
    "登录官方开发者": "Sign in as Official Developer",
    "退出官方开发者": "Sign out Official Developer",
    "Root Developer · 最高技术权限": "Root Developer · Highest Technical Authority",
    "退出 Root Developer": "Exit Root Developer",
    "设备加入与信任": "Device Enrollment & Trust",
    "为账户创建设备加入凭据": "Create Device Enrollment Credential",
    "批量导入并创建加入凭据": "Bulk Import and Create Enrollment Credentials",
    "加入现有企业": "Join Existing Enterprise",
    "重新连接企业": "Reconnect Enterprise",
    "企业局域网协调器": "Enterprise LAN Coordinator",
    "启动企业协调器": "Start Enterprise Coordinator",
    "停止企业协调器": "Stop Enterprise Coordinator",
    "启动企业局域网协调器": "Start Enterprise LAN Coordinator",
    "企业连接已重新认证": "Enterprise Connection Reauthenticated",
    "企业重连失败": "Enterprise Reconnection Failed",
})
