"""Static packet-analysis field defaults kept outside the engine hot module."""

PACKET_SUMMARY_FIELDS = (
    "frame.number", "frame.time_epoch", "frame.len", "frame.cap_len", "frame.protocols",
    "_ws.col.Protocol", "_ws.col.Info",
    "eth.src", "eth.dst", "eth.type",
    "vlan.id", "vlan.priority", "vlan.dei",
    "arp.opcode", "arp.src.proto_ipv4", "arp.dst.proto_ipv4", "arp.src.hw_mac", "arp.dst.hw_mac",
    "ip.src", "ip.dst", "ip.version", "ip.hdr_len", "ip.len", "ip.dsfield.dscp", "ip.dsfield.ecn",
    "ip.id", "ip.flags", "ip.frag_offset", "ip.ttl", "ip.proto",
    "ipv6.src", "ipv6.dst", "ipv6.version", "ipv6.plen", "ipv6.hlim", "ipv6.nxt", "ipv6.flow",
    "icmp.type", "icmp.code", "icmp.ident", "icmp.seq",
    "icmpv6.type", "icmpv6.code",
    "tcp.srcport", "tcp.dstport", "tcp.stream", "tcp.seq", "tcp.ack", "tcp.len", "tcp.hdr_len",
    "tcp.flags", "tcp.window_size_value", "tcp.window_size_scalefactor", "tcp.options.mss_val",
    "tcp.options.sack_perm",
    "tcp.options.wscale.shift", "tcp.options.timestamp.tsval", "tcp.options.timestamp.tsecr",
    "udp.srcport", "udp.dstport", "udp.stream", "udp.length",
    "sctp.srcport", "sctp.dstport", "sctp.verification_tag",
    "dns.id", "dns.qry.name", "dns.qry.type", "dns.flags.response", "dns.flags.rcode", "dns.count.answers",
    "dns.resp.type", "dns.resp.ttl",
    "bootp.id", "dhcp.option.dhcp", "dhcpv6.msgtype",
    "tls.record.version", "tls.handshake.type", "tls.handshake.version", "tls.handshake.ciphersuite",
    "tls.handshake.extensions_server_name", "tls.handshake.extensions_alpn_str",
    "tls.handshake.extensions.supported_version",
    "http.request.method", "http.host", "http.request.uri", "http.request.version",
    "http.response.code", "http.response.version", "http.content_type", "http.content_length", "http.user_agent",
    "http2.streamid", "http2.type", "http2.flags", "http2.length", "http2.headers.method",
    "http2.headers.path", "http2.headers.status", "http2.headers.authority",
    "http3.frame_type",
    "quic.stream.stream_id", "quic.version", "quic.long.packet_type", "quic.dcid", "quic.scid",
    "quic.token_length",
    "websocket.opcode", "websocket.payload_length",
    "ssh.protocol", "smtp.req.command", "smtp.response.code", "imap.request", "pop.request.command",
    "ftp.request.command", "sip.Method", "sip.Status-Code", "sip.Call-ID",
    "rtp.ssrc", "rtp.seq", "rtp.timestamp", "rtp.p_type",
    "ntp.flags.mode", "ntp.stratum", "snmp.version", "snmp.pdu_type", "mqtt.msgtype",
    "modbus.func_code", "stun.type", "coap.code", "radius.code", "smb2.cmd",
    "kerberos.msg_type", "ldap.protocolOp",
    "tcp.analysis.retransmission", "tcp.analysis.fast_retransmission",
    "tcp.analysis.spurious_retransmission", "tcp.analysis.out_of_order", "tcp.analysis.lost_segment",
    "tcp.analysis.duplicate_ack", "tcp.analysis.zero_window", "tcp.analysis.window_full",
    "tcp.analysis.keep_alive", "tcp.analysis.bytes_in_flight", "tcp.analysis.ack_rtt",
)
