from __future__ import annotations

import argparse
import pprint
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from arenyxa.infrastructure.atomic_io import atomic_write_text              
from arenyxa.security.developer_credentials import (              
    DeveloperRevocationSet,
    DeveloperTrustStore,
    artifact_sha256,
    load_json_object,
    validate_root_trust,
)
from arenyxa.security.developer_trust_anchors import (              
    EMBEDDED_DEVELOPER_REVOCATIONS,
    EMBEDDED_DEVELOPER_ROOTS,
)


def _render_module(roots: list[dict], revocations: list[dict]) -> str:
    return (
        '"""Build-time Developer Trust anchors for Official Developer Access.\n\n'
        "AUTO-GENERATED BY scripts/embed_developer_root.py. Only public trust material belongs here.\n"
        'Never place Root/Issuing/Developer private keys in the public Arenyxa source tree.\n"""\n\n'
        "EMBEDDED_DEVELOPER_ROOTS = "
        + pprint.pformat(tuple(roots), width=100, sort_dicts=True)
        + "\n\nEMBEDDED_DEVELOPER_REVOCATIONS = "
        + pprint.pformat(tuple(revocations), width=100, sort_dicts=True)
        + "\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Pin a validated Developer Root PUBLIC trust artifact into the Arenyxa build. "
            "Runtime JSON is deliberately not a trust anchor."
        )
    )
    parser.add_argument("root_trust", type=Path)
    parser.add_argument(
        "--additional-root",
        action="append",
        default=[],
        type=Path,
        help="additional trusted public Root artifact during a controlled rotation overlap",
    )
    parser.add_argument(
        "--revocations",
        type=Path,
        help="optional build-time arenyxa.developer-revocation-set/v1 snapshot",
    )
    parser.add_argument(
        "--replace",
        action="store_true",
        help="replace existing embedded roots/revocations instead of extending them",
    )
    args = parser.parse_args()

    current_roots = [] if args.replace else [dict(item) for item in EMBEDDED_DEVELOPER_ROOTS]
    current_revocations = [] if args.replace else [dict(item) for item in EMBEDDED_DEVELOPER_REVOCATIONS]

    incoming = [args.root_trust, *args.additional_root]
    by_id = {str(item["key_id"]): item for item in DeveloperTrustStore(current_roots).roots()}
    for path in incoming:
        root = validate_root_trust(load_json_object(path))
        key_id = str(root["key_id"])
        previous = by_id.get(key_id)
        if previous is not None and artifact_sha256(previous) != artifact_sha256(root):
            raise SystemExit(f"Refusing conflicting Developer Root artifact for key_id {key_id}")
        by_id[key_id] = root

    revocations = current_revocations
    if args.revocations is not None:
        revocations.extend(dict(item) for item in DeveloperRevocationSet.load(args.revocations).values)
                                                                                                          
    unique_revocations: dict[str, dict] = {}
    for item in revocations:
        unique_revocations[artifact_sha256(item)] = dict(item)

    roots = [by_id[key] for key in sorted(by_id)]
    revocations = [unique_revocations[key] for key in sorted(unique_revocations)]
                                                                                              
    DeveloperTrustStore(roots)
    DeveloperRevocationSet(revocations)

    target = ROOT / "src" / "arenyxa" / "security" / "developer_trust_anchors.py"
    atomic_write_text(target, _render_module(roots, revocations), newline="\n")
    print(f"Embedded Developer Root public anchors: {len(roots)}")
    for root in roots:
        print(f"  {root['key_id']}  {root['fingerprint']}")
    print(f"Embedded revocations: {len(revocations)}")
    print(f"Target: {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
